### ISSUE TITLE
New uploads not working

### ISSUE THREAD

**Issue by gianfranco-s** [tomaspf9/ReadMyDuck#22]

**Comment by tomaspf9** [comment]
Previous #23 didn't resolve the issue.
When I enter http://127.0.0.1:3000/,

My file is correctly uploaded. I can see it both in 'upload' and in the front as shown in the image
![shownfront](https://github.com/tomaspf9/ReadMyDuck/assets/84751753/3cad4c7f-a9b1-48c6-b4ca-f2838de844dc)
![image](https://github.com/tomaspf9/ReadMyDuck/assets/84751753/1d3b579a-54b5-4011-aa16-730deb13e793)

Then I visualize this error:
![image](https://github.com/tomaspf9/ReadMyDuck/assets/84751753/ecdb449c-fb89-43b1-a900-dbe50efd2013)

And then when I do a query in the chatbot, it resonds from a different context, like another document.

**Comment by tomaspf9** [comment]
What I tried:

I deleted 'upload' and 'faiss_index' to see if it could start over, but it didn't work. It just persisted in responding from my other documents previously loaded.
